# Base stage with Node.js
FROM node:18-alpine AS base
WORKDIR /workspace/src

# Dependencies stage, installing required packages
FROM base AS deps
COPY package.json yarn.lock ./

RUN yarn install

# Development stage
FROM base AS dev

# Copy installed dependencies from the deps stage
COPY --from=deps /workspace/src/node_modules ./node_modules

EXPOSE 3000
CMD [ "yarn", "dev" ]

