version: '3.9'
services:
  dev:
    image: threads-clone-dev 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace/src/
      - /workspace/src/node_modules
    ports:
      - "3000:3000"
    profiles: ["dev"]
  prod:
    image: threads-clone-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    profiles: ["prod"]
